package fr.uca.miage.sevenwonders.models;

import fr.uca.miage.sevenwonders.models.card.Card;

import org.junit.jupiter.api.Test;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for the {@code Cost} interface and its record implementations.
 * <p>
 * This test class verifies the instantiation and state of the new {@code Cost}
 * records (Free, Gold, Materials, Compound, Trading) using their public
 * constructors and accessor methods (which are automatically generated by
 * records), eliminating the need for reflection.
 * </p>
 */
class CostTest {

    /**
     * Verifies the instantiation and state of the {@link Cost.Free} record.
     */
    @Test
    void testCostFreeInstantiationAndState() {
        // Use the static factory method
        Cost.Free cost = (Cost.Free) Cost.free();

        assertNotNull(cost, "Cost.Free object should be created successfully.");
        assertTrue(cost instanceof Cost, "Cost.Free should implement the Cost interface.");
    }

    /**
     * Verifies the instantiation and state of the {@link Cost.Gold} record.
     */
    @Test
    void testCostGoldInstantiationAndState() {
        int expectedAmount = 5;
        // Use the static factory method
        Cost.Gold cost = (Cost.Gold) Cost.gold(expectedAmount);

        assertNotNull(cost, "Cost.Gold object should be created successfully.");
        assertTrue(cost instanceof Cost, "Cost.Gold should implement the Cost interface.");
        // Records automatically provide an accessor method named after the field
        assertEquals(expectedAmount, cost.amount(),
                "The gold amount should match the value passed to the constructor.");
    }

    /**
     * Verifies the instantiation and state of the {@link Cost.Materials} record.
     */
    @Test
    void testCostMaterialsInstantiationAndState() {
        Card.Materials[] expectedMaterials = {Card.Materials.WOOD, Card.Materials.STONE};
        // Use the static factory method
        Cost.Materials cost = (Cost.Materials) Cost.materials(expectedMaterials);

        assertNotNull(cost, "Cost.Materials object should be created successfully.");
        assertTrue(cost instanceof Cost, "Cost.Materials should implement the Cost interface.");

        // Check the materials array
        assertArrayEquals(expectedMaterials, cost.materials(),
                "The materials array should match the one passed to the constructor.");
    }

    /**
     * Verifies the {@link Cost.Materials} record handles a null or empty array
     * gracefully.
     */
    @Test
    void testCostMaterialsWithNullOrEmptyArray() {
        // Test with null array (should result in an empty array due to canonical
        // constructor in Cost.java)
        Cost.Materials costNull = new Cost.Materials(null);
        assertNotNull(costNull.materials(), "Internal materials array should not be null.");
        assertEquals(0, costNull.materials().length, "Internal materials array should be empty if null is passed.");

        // Test with empty array
        Cost.Materials costEmpty = new Cost.Materials(new Card.Materials[0]);
        assertEquals(0, costEmpty.materials().length, "Internal materials array should be empty.");
    }

    /**
     * Verifies the instantiation and state of the {@link Cost.Compound} record
     * using the varargs constructor.
     */
    @Test
    void testCostCompoundInstantiationAndState() {
        Cost goldCost = Cost.gold(3);
        Cost materialsCost = Cost.materials(Card.Materials.CLAY);

        // The factory method Cost.compound() returns Cost, so it must be cast to
        // Cost.Compound
        Cost.Compound cost = (Cost.Compound) Cost.compound(goldCost, materialsCost);

        assertNotNull(cost, "Cost.Compound object should be created successfully.");
        assertTrue(cost instanceof Cost, "Cost.Compound should implement the Cost interface.");

        List<Cost> costs = cost.costs();
        assertNotNull(costs, "The costs list should not be null.");
        assertEquals(2, costs.size(), "The costs list should contain two elements.");
        assertSame(goldCost, costs.get(0), "The first cost should be the gold cost.");
        assertSame(materialsCost, costs.get(1), "The second cost should be the materials cost.");
    }
}
